version: "3.9"
services:
  db-image-processing:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - image_processing_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: [postgres]

  db-result-retrieval:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: result_retrieval_db
    ports:
      - "5433:5432"
    volumes:
      - result_retrieval_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d result_retrieval_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - db-image-processing
    command: [postgres]

  alembic-service:
    build: ./db_maintenance
    depends_on:
      - db-image-processing
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DB_IMAGE_PROCESSING_HOST: db-image-processing
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - alembic-models:/app/db_models # mount db models for alembic
    command: ["python", "main.py"]

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:80"
    depends_on:
      - db-result-retrieval
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    restart: always

volumes:
  image_processing_db_data:
  result_retrieval_db_data:
  alembic-models:
  pgadmin_data: